### ISSUE TITLE
Event feedback: Prompt Feedback on Attended Events

### ISSUE THREAD

**Issue by farisashai** [acmucsd/membership-portal-ui-v2#121]
Instead of showing a list of the most recent past events on the home page which provides very little value to a user, show them a list of past events that they've attended (if they have any attendences) and ask them if they want to leave feedback for the event to help improve the quality of ACM (feedback route has existed on the portal api for years but never been used so I don't know if it works correctly and saves to a table somewhere in the database - validate this first with backend) 

- [ ] Users should be able to submit event feedback after having attended an event
- [ ] Make buttons on checkin/event modal that prompt for feedback

References:

- acmucsd/membership-portal#114
- acmucsd/membership-portal#133
- acmucsd/membership-portal#412
- [Figma: feedback submissions](https://www.figma.com/file/tv9hYPFP0HPGGXgonS5Jvw/Portal---Mobile-Only-Redesign?type=design&node-id=0-4848&mode=design&t=yEfkAYi3wJH18mmb-4)
- [Figma: feedback form](https://www.figma.com/file/tv9hYPFP0HPGGXgonS5Jvw/Portal---Mobile-Only-Redesign?type=design&node-id=0-4981&mode=design&t=yEfkAYi3wJH18mmb-4)
- [Figma: attended event feedback](https://www.figma.com/file/tv9hYPFP0HPGGXgonS5Jvw/Portal---Mobile-Only-Redesign?type=design&node-id=0-2766&mode=design&t=yEfkAYi3wJH18mmb-4)

![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/22133785/f183c77a-1ae7-4a72-8591-30ce8276477b)

![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/22133785/cfce17aa-df67-4ff3-9909-aadb0256929e)

**Comment by SheepTester** [comment]
Is this a duplicate of #139

**Comment by farisashai** [comment]
Technically #139 is a duplicate of this but the one difference I mentioned here is that we should replace the cards shown under "Past Events" carousel on the home page with the user's past attended events instead of just recent events that happened if the user didn't go to them
