### ISSUE TITLE
Auth Token Expiration Handling

### ISSUE THREAD

**Issue by alexzhang1618** [acmucsd/membership-portal-ui-v2#13]
- If the authentication token we use to make requests to the backend expires, we should remove our current session tokens and move the user to the login page

**Comment by farisashai** [comment]
We should check with backend if the bearer tokens on the Portal API ever expire. If they don't, we can close this issue

**Comment by farisashai** [comment]
Confirmed with Shravan that bearer auth tokens on the backend last exactly 2 weeks as set in an environment variable so we should match this convention when we set the AUTH_TOKEN cookie on login using the options argument seen here for `maxAge`. 

https://www.npmjs.com/package/cookies-next

![Screenshot 2023-04-09 at 3 41 01 AM](https://user-images.githubusercontent.com/33165426/230768013-1c4107a4-f95f-46e5-86d8-1c2324e351c2.jpg)
