### ISSUE TITLE
Sync Dark Mode transitions

### ISSUE THREAD

**Issue by alexzhang1618** [acmucsd/membership-portal-ui-v2#135]
- some items (bold vs. unbolded text, icons, etc.) don't transition at the same time as others when light vs. dark mode is toggled

https://github.com/acmucsd/membership-portal-ui-v2/assets/27360825/addb50a0-2a76-4eae-a963-48b691ad68c3

**Comment by WishingWell13** [comment]
https://paco.me/writing/disable-theme-transitions

This sounds promising

https://github.com/pacocoursey/next-themes?tab=readme-ov-file (search disabledTransitionOnChange)
