### ISSUE TITLE
Horizontally center align leaderboard top 3 name and rank

### ISSUE THREAD

**Issue by farisashai** [acmucsd/membership-portal-ui-v2#155]
See 1st and 3rd cards below 

![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/33165426/3b5ea103-f24c-4a44-b38a-66b8ecdc7dc0)

**Comment by SheepTester** [comment]
vertical? this looks like a horizontal centering problem to me

**Comment by farisashai** [comment]
u know what i meant 👿
