### ISSUE TITLE
Blank Recently Attended Events

### ISSUE THREAD

**Issue by farisashai** [acmucsd/membership-portal-ui-v2#189]
If you jump to the end of the leaderboard for someone with no points, they have this awkward little div here with nothing in it
<img width="909" alt="image" src="https://github.com/acmucsd/membership-portal-ui-v2/assets/33165426/cad147ac-f09c-4eff-b2c6-2fc3d381919d">

we should put a message here like "This person hasn't been to any ACM events yet." or smth or fill the space with a sad cat image

**Comment by SheepTester** [comment]
should've been added in #184, no?

**Comment by SheepTester** [comment]
never mind alex missed it in both #184 and #186 :skull: we should probably just make it a component so it doesnt happen again

**Comment by alexzhang1618** [comment]
I'll rewrite so we use eventcarousel instead

**Comment by alexzhang1618** [comment]
this'll let us do a funny picture

**Comment by alexzhang1618** [comment]
> never mind alex missed it in both #184 and #186 💀 we should probably just make it a component so it doesnt happen again

I wouldn't say missed I prefer strategically avoided
