### ISSUE TITLE
Share Resume button doesn't toggle

### ISSUE THREAD

**Issue by farisashai** [acmucsd/membership-portal-ui-v2#192]
why is nothing happening when i click it
https://github.com/acmucsd/membership-portal-ui-v2/assets/33165426/2e6048a8-9e92-453e-8d8f-2e26add7ee6d

the display attendance history one works fine

**Comment by SheepTester** [comment]
Guessing it's because you don't have a resume uploaded. Should probably just hide it until you upload a resume since that option is stored with the resume object
