### ISSUE TITLE
Create About Page

### ISSUE THREAD

**Issue by raymosun** [acmucsd/membership-portal-ui-v2#39]
Implement this slight redesign of about page on the new portal (desktop and mobile friendly).

You can probably reference the code for this page on the old portal.

![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/30709485/8f938444-2352-4342-971e-c33ed12ced64)
[link to figma](https://www.figma.com/file/WCc4V3sy05iF55BRum71Mv/Portal-UI-v2-Pages?type=design&node-id=22-824&t=lE8Xy66AHrvLfESP-0)

**Comment by trevorkw7** [comment]
For the mobile version of this page, it's probably fine to remove the Discord embed to make the UI less busy.
