### ISSUE TITLE
Create Storefront Page

### ISSUE THREAD

**Issue by raymosun** [acmucsd/membership-portal-ui-v2#52]
Create the storefront at `/store` based on these [figma designs](https://www.figma.com/file/cgbeW6vrqgxW0i1vpbUn1C/Store-(Redesign-2023)?type=design&node-id=654-2155&mode=design&t=jCa9Nm6GIE583hHg-0) (check the 'ready for dev' sections).

Requires #54 and #53

This issue encompasses
- Desktop layout for storefront
- Mobile layout for storefront
- Help Modal for first time users
- Toggle between 'Collections' and 'All Items' viewing modes
  - Collection Card component (Browse collections)
  - Collection Slider component (Browse all items)

![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/30709485/db0a28e8-df25-411c-b4a5-fea1346e1ab3)

**Comment by SheepTester** [comment]
https://github.com/acmucsd/membership-portal-ui-v2/assets/22133785/52758e12-f701-4dd5-b0ce-2bad82046589

I implemented the mobile help modal pagination thing with pure CSS using scroll snapping, which feels kind of sussy so hopefully it works in not-Chrome

**Comment by farisashai** [comment]
Closed in #64
