### ISSUE TITLE
Create Store Collection Page

### ISSUE THREAD

**Issue by raymosun** [acmucsd/membership-portal-ui-v2#55]
Implement store collections page at `/store/collection/[collection-uuid]` based on these [figma designs](https://www.figma.com/file/cgbeW6vrqgxW0i1vpbUn1C/Store-(Redesign-2023)?type=design&node-id=654-2155&mode=design&t=jCa9Nm6GIE583hHg-0) (check the 'ready for dev' sections).

Requires #53 and #54.

This issue compasses:
- Desktop layout for collection
- Mobile layout for collection

![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/30709485/ff718bf3-3107-4583-bee3-c653b813c918)

**Comment by SheepTester** [comment]
Closed by #92
