### ISSUE TITLE
Create Store 'My Orders' Page

### ISSUE THREAD

**Issue by raymosun** [acmucsd/membership-portal-ui-v2#58]
Implement Store Orders page at `/store/orders` based on these [figma designs](https://www.figma.com/file/cgbeW6vrqgxW0i1vpbUn1C/Store-(Redesign-2023)?type=design&node-id=654-2155&mode=design&t=jCa9Nm6GIE583hHg-0) (check the 'ready for dev' sections). 

Requires #54.

Encompasses:
- Desktop layout for orders page
- Mobile layout for orders page
- Collapsible order component
- Filtering orders

![image](https://github.com/acmucsd/membership-portal-ui-v2/assets/30709485/44a922af-3967-4a6b-9aaa-336a3961d2b9)

**Comment by farisashai** [comment]
Closed in #102
