### ISSUE TITLE
Implement leaderboard search and "my position" feature

### ISSUE THREAD

**Issue by trevorkw7** [acmucsd/membership-portal-ui-v2#62]
1. Add the leaderboard search function, which should perform a linear search on the "leaderboard" object returned from backend and replaces the leaderboard with search results in the same styling as leaderboard rows. 
2. Add the "my position feature" which scrolls the user down the leaderboard to the position they're currently in.

<img width="847" alt="image" src="https://github.com/acmucsd/membership-portal-ui-v2/assets/54345106/f33fe9f6-a83f-4a2c-bebe-b6f7b14f503b">

**Comment by SheepTester** [comment]
Added in #69. Not sure why the trigger word in the PR didn't work
